### ISSUE TITLE
'Could not read from remote repository'

### ISSUE THREAD

**Issue by guillaumelegros** [disordered-photonics/celes#10]
Dear colleagues,
I am trying to run your exciting code. I got the following message when cloning celes as prescribed in readme.md:

git clone git@github.com:disordered-photonics/celes.git
Cloning into 'celes'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Did I miss a step?
Best regards,

Guillaume Legros
http://www.dalembert.upmc.fr/home/legros/

**Comment by gmazzamuto** [comment]
Dear Guillaume,

thanks for your interest in CELES!

Please try using https instead of the git protocol like this:
git clone https://github.com/disordered-photonics/celes.git

that should work

hope this helps!
Giacomo
