### ISSUE TITLE
catch case of few spheres before calling convHull

### ISSUE THREAD

**Issue by AmosEgel** [disordered-photonics/celes#21]
The method `compute_maximal_particle_distance` calls `convhull` which raises an error if the particle number is below 4.

**Comment by lpattelli** [comment]
uh, I did not notice this problem. However, I think this should be already fixed by commit 3ce1942ca632d3cc8a2d59d0caed992a2f880d41 on the develop branch, even though it was meant to fix another issue.

**Comment by AmosEgel** [comment]
Ah, indeed - great!
