### ISSUE TITLE
Celes: solve "periodic particle array" problem with "plane wave sources".

### ISSUE THREAD

**Issue by tuyen-le** [disordered-photonics/celes#27]
Dear authors,

This code seems to be not able to solve "periodic particle array" problem with "plane wave sources".

Do you have any updated version of Celes to add a "periodic particle array" boundary condition inside code?

Thank you!

Le

**Comment by AmosEgel** [comment]
Hi Le,

unfortunately, CELES doesn't support periodic boundary conditions. You might want to ask [Dominik Theobald from Karlsruhe Institute of Technology](https://www.lti.kit.edu/mitarbeiter_7350.php). He is currently working on a code for periodic arrays.

**Comment by tuyen-le** [comment]
Dear Mr. Egel,

Thank you for your reply and suggestion. I will contact Mr. Theobald soon.

Le
