### ISSUE TITLE
Environment issue

### ISSUE THREAD

**Issue by lpf1143** [disordered-photonics/celes#29]
Hi!
Thanks for developing this!  Due to the SSD failure, our desktop that was able to run this program crashed, and we fail to retrive the relevant information related to environment and software version. We tried to rebuild the environment, but in newer version of matlab and cuda (2021a with CUDA 10.2, 11), we get this error message 

```
number of particles: 500
compiling CUDA-code with lmax=3.
Building with 'NVIDIA CUDA Compiler'.
Error using mex
ptxas fatal   : Unresolved extern function '_Z3powfi'
nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35', 'sm_37' and 'sm_50' architectures are deprecated, and may be removed in a future release
(Use -Wno-deprecated-gpu-targets to suppress warning).
coupling_matrix_multiply_CUDA.cu



Error in mexcuda (line 168)
    [varargout{1:nargout}] = mex(mexArguments{:});

Error in cuda_compile (line 73)
    mexcuda(verb_flag, DEFINES, '-outdir', script_dir, '-output', OUT_FILE, SRC_FILE)

Error in celes_simulation/run (line 394)
                cuda_compile(obj.numerics.lmax);

Error in CELES_MAIN (line 114)
simul.run;
 ```

We also tried the combination of 2017b, cuda8.0 and visual studio 15, but some error related to compiler pops up

```
Error using mex
No supported compiler or SDK was found. For options, visit https://www.mathworks.com/support/compilers.
Error in mexcuda (line 157)
    [varargout{1:nargout}] = mex(mexArguments{:});
Error in cuda_compile (line 73)
    mexcuda(verb_flag, DEFINES, '-outdir', script_dir, '-output', OUT_FILE, SRC_FILE)
Error in celes_simulation/run (line 394)
                cuda_compile(obj.numerics.lmax);
Error in CELES_MAIN (line 114)
simul.run;
```

Does anyone have ideas how to solve it? Thanks!

**Comment by Hanqi-Lin** [comment]
Tried 2017b, cuda8.0 and visual studio 17 and problem solved, but still curious why it cannot be run on newer version of matlab and cuda. is it because some of the functions are  deprecated in newer version? Seems "nvcc warning" just related to some old GPU architechture.
