### ISSUE TITLE
Analysis of multiple wavelengths

### ISSUE THREAD

**Issue by SoulEater45** [disordered-photonics/celes#31]
I am currently analyzing the behavior of particle clusters under different wavelengths. For this, I need the expansion coefficients **a** and **f**, which are provided by the tables properties of the simulation class (initialFieldCoefficients and scatteredFieldCoefficients). Since celes can only accept a single wavelength, I need to rerun the same code multiple times, which does take a lot of time. I noticed that the run function of the simulation class accepts an initial guess of the scattered field coefficients **f0**, so I am using the coefficients of the previous run to initialize them. My reason behind this is that the field should not differ much by changing the wavelength slightly. I have not found similar parameters where I could provide some initial guesses in the preconditioner class, which takes also quite a long time to finish.
I was wondering if someone could advise me on how I could speed up things.
Thanks for the help!

**Comment by AmosEgel** [comment]
The initial guess for the simulation run is used in an iterative solver of the linear system. The iterative solvers starts from some initial value and reiterates some algorithm that hopefully converges to the correct solution. The philosophy of the initial guess is that if the initial value of the iterative solver is already close to the actual solution, the solver might need fewer iterations until it converges to the solution. 

The preconditioner on the other hand does not apply any iterative solver, but it is based on matrix inversion. For that reason, I see no possibility to apply an initial guess for that step.

**Comment by SoulEater45** [comment]
Thanks for the reply @AmosEgel and @lpattelli 
I have taken the preconditioner out and reduced the time from 38 minutes to 11 minutes in my test case. Is the preconditioner relevant for calculating the coefficients? If not, maybe I can skip some of the unnecessary calculations and speed it up a bit.
